language: csharp
mono: none
dotnet: 2.1.4
install:
- cd Punch.Web && npm install
- dotnet restore

script:
 - dotnet build

deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true
  on:
   branch: master